# Generated by Django 4.2.7 on 2024-01-04 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_article_post_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='article',
            name='post_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
